apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    k8s-app: sample-service
    app.kubernetes.io/component: monitoring   # Mandatory label
  name: sample-service
spec:
  podMetricsEndpoints:
  - interval: 30s
    targetPort: 14269
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: sample-service