{
 "title": "Alerts - Overview",
 "description": "Show current firing and pending alerts, and  severity alert counts.",
 "tags": [ "alerts" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$cluster\"}, exported_namespace)"
    }
   },
   { "name": "severity", "query": { "query": "label_values(ALERTS, severity)" } }
  ]
 },
 "panels": [
  { "title": "Alerts Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts",
   "type": "stat",
   "description": "Show the number of alerts  (all alerts, sent to alertmanager, pending sent to alertmanager)",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertname!=\"DeadMansSwitch\", cluster=~\"$cluster\"})",
     "legendFormat": "All alerts"
    },
    {
     "expr": "sum(ALERTS{alertname!=\"DeadMansSwitch\",alertstate=\"firing\", cluster=~\"$cluster\"} > 0) ",
     "legendFormat": "Firing"
    },
    {
     "expr": "sum(ALERTS{alertname!=\"DeadMansSwitch\",alertstate=\"pending\", cluster=~\"$cluster\"} > 0)",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "stat",
   "description": "Show the number of alerts with \"critical\" severity",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(ALERTS{alertname!=\"DeadMansSwitch\",alertstate=\"firing\",severity=~\"(?i:(Critical))\", cluster=~\"$cluster\"} -0 > 0) ",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ]
    }
   ]
  },
  {
   "title": "High",
   "type": "stat",
   "description": "Show the number of alerts with \"high\" severity",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertname!=\"DeadMansSwitch\",alertstate=\"firing\",severity=~\"(?i:(high))\", cluster=~\"$cluster\"} - 0 > 0) "
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "description": "Show the number of alerts with \"warning\" severity",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertname!=\"DeadMansSwitch\", alertstate=\"firing\",severity=~\"(?i:(warning))\", cluster=~\"$cluster\"} -0 > 0) "
    }
   ]
  },
  {
   "title": "Info",
   "type": "stat",
   "description": "Show the number of alerts with \"info\" severity",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertname!=\"DeadMansSwitch\",alertstate=\"firing\",severity=~\"(?i:(info))\", cluster=~\"$cluster\"} -0 > 0) "
    }
   ]
  },
  {
   "title": "Other Labels",
   "type": "stat",
   "description": "Show the number of alerts without severity",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertname!=\"DeadMansSwitch\",alertstate=\"firing\",severity!~\"(?i:(critical|high|warning|info|))\", cluster=~\"$cluster\"} -0 > 0) "
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Firing",
     "type": "table",
     "description": "Show the table with alerts in firing state, which group by alertnames, namespaces, severities",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "ALERTS{alertname!=\"DeadMansSwitch\", severity=~\"$severity\",alertstate='firing', exported_namespace=~\"$namespace|\", cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Pending",
     "type": "table",
     "description": "Show the table with alerts in a pending state, which group by alertnames, namespaces, severities",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "ALERTS{alertname!=\"DeadMansSwitch\", severity=~\"$severity\",alertstate=\"pending\", exported_namespace=~\"$namespace|\", cluster=~\"$cluster\"}"
      }
     ]
    }
   ]
  }
 ]
}