{
 "title": "CoreDNS",
 "description": "A dashboard for the CoreDNS DNS server.",
 "tags": [
  "k8s",
  "coredns",
  "dns"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(coredns_plugin_enabled, cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(coredns_build_info{cluster=\"$cluster\"}, instance)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(coredns_build_info{cluster=\"$cluster\", instance=~\"$instance\"}, pod)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(coredns_build_info{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(coredns_build_info{cluster=\"$cluster\"}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests (total)",
   "type": "timeseries",
   "description": "Shows total requests by protocol (udp, tcp)",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\",instance=~\"$instance\"}[5m])) by (proto)",
     "legendFormat": "{{proto}}"
    }
   ]
  },
  {
   "title": "Failed config reload",
   "type": "timeseries",
   "description": "Shows count of failed config CoreDNS reload by pod",
   "gridPos": { "h": 9, "w": 8, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "coredns_reload_failed_total{cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{ node }} - {{ pod }}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Shows CoreDNS version",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by(version)(coredns_build_info{cluster=\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Enabled plugins",
   "type": "table",
   "description": "Shows enabled plugins for CoreDNS",
   "gridPos": { "h": 15, "w": 5, "x": 19, "y": 3 },
   "targets": [
    {
     "expr": "group by (name) (coredns_plugin_enabled{cluster=~\"$cluster\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Responses (duration)",
   "type": "timeseries",
   "description": "Shows request duration",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{cluster=\"$cluster\",instance=~\"$instance\"}[5m])) by (le, job))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "CoreDNS panics",
   "type": "timeseries",
   "description": "Shows total number of panics.",
   "gridPos": { "h": 9, "w": 8, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "coredns_panics_total{cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{ node }} - {{ pod }}"
    }
   ]
  },
  {
   "title": "Requests (by qtype)",
   "type": "timeseries",
   "description": "Shows count of DNS request by type",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\",instance=~\"$instance\"}[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests (by zone)",
   "type": "timeseries",
   "description": "Shows count of requests by zone",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\",instance=~\"$instance\"}[5m])) by (zone)",
     "legendFormat": "zone: {{zone}}"
    }
   ]
  },
  {
   "title": "Responses (by rcode)",
   "type": "timeseries",
   "description": "Count of responses grouped by code",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{cluster=\"$cluster\",instance=~\"$instance\"}[5m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Responses (size, udp/tcp)",
   "type": "timeseries",
   "description": "Response size for \"udp/tcp\" protocol",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{cluster=\"$cluster\",instance=~\"$instance\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{instance=\"$instance\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:50%"
    }
   ]
  },
  {
   "title": "Requests (size, udp/tcp)",
   "type": "timeseries",
   "description": "Request size for \"udp/tcp\" protocol",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{cluster=\"$cluster\",instance=~\"$instance\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:50%"
    }
   ]
  },
  {
   "title": "Cache (hitrate)",
   "type": "timeseries",
   "description": "Counter of cache hits by cache type.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{cluster=\"$cluster\",instance=~\"$instance\"}[5m])) by (type)",
     "legendFormat": "hits:{{type}}"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total{instance=~\"$instance\"}[5m])) by (type)",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Cache (count)",
   "type": "timeseries",
   "description": "Total elements in the cache by cache type.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coredns_cache_entries{cluster=\"$cluster\",instance=~\"$instance\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}