{
 "title": "Kubernetes / Etcd",
 "description": "Etcd Dashboard for Prometheus metrics scraper",
 "tags": [
  "k8s",
  "etcd"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "interval",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Etcd has a leader?",
   "type": "stat",
   "description": "Indicates whether the members have a leader.\n\nYes - all members have a leader.\nNo - one or more members haven't a leader.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{cluster=\"$cluster\"})/sum(up{cluster=\"$cluster\", job=\"etcd\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Leader name",
   "type": "stat",
   "description": "Indicate which server is the leader",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(etcd_server_is_leader{cluster=\"$cluster\"} == 1)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Disk operations wal_fsync duration",
   "type": "timeseries",
   "description": "The latency distributions of fsync called by wal",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{cluster=\"$cluster\"}[$interval])) by (pod, le))",
     "legendFormat": "{{ pod }} WAL fsync"
    }
   ]
  },
  {
   "title": "Count of leader changes per $interval",
   "type": "timeseries",
   "description": "Show the number of leader changes per $interval",
   "gridPos": { "h": 10, "w": 6, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{cluster=~\"$cluster\", service=~\".*etcd.*\"}[$interval]) ",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "The sum of leader changes",
   "type": "stat",
   "description": "Show the sum of leader changes per $interval",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(changes(etcd_server_leader_changes_seen_total{cluster=~\"$cluster\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Etcd nodes status",
   "type": "state-timeline",
   "description": "Shows status of each etcd pod in the cluster.",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "up{endpoint=~\".*metrics\",job=\"etcd\",cluster=\"$cluster\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "The sum rate of failed proposals seen",
   "type": "stat",
   "description": "Show the sum rate of failed proposals seen per $interval",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{cluster=\"$cluster\"}[$interval]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "timeseries",
   "description": "Total number of gRPC's started and failed on the server",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\",cluster=\"$cluster\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\",cluster=\"$cluster\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "timeseries",
   "description": "Show active streams",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\",cluster=\"$cluster\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\",cluster=\"$cluster\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\",cluster=\"$cluster\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\",cluster=\"$cluster\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "timeseries",
   "description": "Total size of the underlying database",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{cluster=\"$cluster\", service=~\".*etcd.*\"}",
     "legendFormat": "{{pod}} DB Size"
    },
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes{cluster=\"$cluster\", service=~\".*etcd.*\"}",
     "legendFormat": "{{pod}} DB Size"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "timeseries",
   "description": "The latency distributions of fsync called by wal and backend",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{cluster=\"$cluster\", service=~\".*etcd.*\"}[5m])) by (pod, le))",
     "legendFormat": "{{ pod }} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{cluster=\"$cluster\", service=~\".*etcd.*\"}[5m])) by (pod, le))",
     "legendFormat": "{{ pod }} DB fsync"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Resident memory size",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"etcd\",cluster=\"$cluster\"}",
     "legendFormat": "{{pod}} Resident Memory"
    }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "timeseries",
   "description": "The total number of bytes received from grpc clients",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{cluster=\"$cluster\", service=~\".*etcd.*\"}[5m])",
     "legendFormat": "{{pod}} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "timeseries",
   "description": "The total number of bytes sent to grpc clients",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{cluster=\"$cluster\", service=~\".*etcd.*\"}[5m])",
     "legendFormat": "{{pod}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "timeseries",
   "description": "The total number of bytes received from peers",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{cluster=\"$cluster\"}[5m])) by (pod)",
     "legendFormat": "{{pod}} Peer Traffic In"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "timeseries",
   "description": "The total number of bytes sent to peers",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{cluster=\"$cluster\"}[5m])) by (pod)",
     "legendFormat": "{{pod}} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "timeseries",
   "description": "The total number of failed proposals seen\n\nThe current number of pending proposals to commit\n\nThe total number of consensus proposals applied, committed",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{cluster=\"$cluster\"})",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Total Leader Elections Per Day",
   "type": "timeseries",
   "description": "The number of leader changes seen per day",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{cluster=\"$cluster\", service=~\".*etcd.*\"}[1d])",
     "legendFormat": "{{pod}} Total Leader Elections Per Day"
    }
   ]
  },
  {
   "title": "The total number of consensus proposals committed",
   "type": "timeseries",
   "description": "proposals_committed_total records the total number of consensus proposals committed. This gauge should increase over time if the cluster is healthy. Several healthy members of an etcd cluster may have different total committed proposals at once. This discrepancy may be due to recovering from peers after starting, lagging behind the leader, or being the leader and therefore having the most commits. It is important to monitor this metric across all the members in the cluster; a consistently large lag between a single member and its leader indicates that member is slow or unhealthy.\n\nproposals_applied_total records the total number of consensus proposals applied. The etcd server applies every committed proposal asynchronously. The difference between proposals_committed_total and proposals_applied_total should usually be small (within a few thousands even under high load). If the difference between them continues to rise, it indicates that the etcd server is overloaded. This might happen when applying expensive queries like heavy range queries or large txn operations.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Total number of consensus proposals committed"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Total number of consensus proposals applied"
    }
   ]
  },
  {
   "title": "Proposals pending",
   "type": "timeseries",
   "description": "indicates how many proposals are queued to commit. Rising pending proposals suggests there is a high client load or the member cannot commit proposals.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(etcd_server_proposals_pending{cluster=\"$cluster\"})",
     "legendFormat": "Proposals pending"
    }
   ]
  },
  {
   "title": "Disks operations",
   "type": "timeseries",
   "description": "The sum rate latency distributions of fsync called by wal and backend",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_disk_wal_fsync_duration_seconds_sum{cluster=\"$cluster\"}[2m]))",
     "legendFormat": "\tThe latency distributions of fsync called by wal"
    },
    {
     "expr": "sum(rate(etcd_disk_backend_commit_duration_seconds_sum{cluster=\"$cluster\"}[2m]))",
     "legendFormat": "The latency distributions of commit called by backend"
    }
   ]
  },
  {
   "title": "Slow Operations",
   "type": "timeseries",
   "description": "The count of slow apply and read index operations ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(etcd_server_slow_apply_total{cluster=\"$cluster\"}[2m])",
     "legendFormat": "{{ pod }} Slow Applies"
    },
    {
     "expr": "rate(etcd_server_slow_read_indexes_total{cluster=\"$cluster\"}[2m])",
     "legendFormat": "{{ pod }} Slow Read Indexes"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "description": "The rate number of bytes received and sent from grpc clients",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_client_grpc_received_bytes_total{cluster=\"$cluster\"}[2m]))",
     "legendFormat": "The total number of bytes received by grpc clients"
    },
    {
     "expr": "sum(rate(etcd_network_client_grpc_sent_bytes_total{cluster=\"$cluster\"}[2m]))",
     "legendFormat": "The total number of bytes sent to grpc clients"
    }
   ]
  },
  {
   "title": "Snapshot Duration",
   "type": "timeseries",
   "description": "Abnormally high snapshot duration (snapshot_save_total_duration_seconds) indicates disk issues and might cause the cluster to be unstable.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_debugging_snap_save_total_duration_seconds_sum{cluster=\"$cluster\"}[2m]))",
     "legendFormat": "The total latency distributions of save called by snapshot"
    }
   ]
  },
  {
   "title": "Snapshot Fsync Duration",
   "type": "timeseries",
   "description": "The latency distributions of fsync called by snap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(etcd_snap_fsync_duration_seconds_sum[5m])",
     "legendFormat": "{{ pod }} Snapshot fsync duration"
    }
   ]
  },
  {
   "title": "Snapshot DB File Duration",
   "type": "timeseries",
   "description": "The latency distributions of saving and fsyncing `.snap.db` files. ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(etcd_snap_db_save_total_duration_seconds_sum[5m])",
     "legendFormat": "{{ pod }} Snapshot DB files total save duration"
    },
    {
     "expr": "rate(etcd_snap_db_fsync_duration_seconds_sum[5m])",
     "legendFormat": "{{ pod }} Snapshot DB files  fsync duration"
    }
   ]
  }
 ]
}