{
 "title": "Go Processes",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "tags": [
  "process",
  "golang"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(go_info, cluster)" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes{cluster=\"$cluster\",job!=\"kube-apiserver\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes{cluster=\"$cluster\",namespace=\"$namespace\", job!=\"kube-apiserver\"}, pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes{cluster=\"$cluster\",namespace=\"$namespace\", job!=\"kube-apiserver\", pod=\"$pod\"}, container)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Go Processes Help",
     "type": "text",
     "description": "Show a short help which describe dashboard and any specific cases show data",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "options": {
      "content": "This dashboard designed to show statistic about any Go processes.\n\nAlmost all metrics collected from any Go process with using [Prometheus golang client](https://github.com/prometheus/client_golang) which Prometheus recommended to ue for instrumetation in [official documents](https://prometheus.io/docs/instrumenting/clientlibs/).\n\nTo view metrics about Go processes within different pods, you can use the variables at the top of the page and switch between different namespaces and pods and containers into them. Variables allow to choose only those namespaces, pods, contains for which Prometheus collected metrics. By choosing a namespace, you filter the pod list by selected namespace. A similar filter is applied to the variable with container name. List of namespaces, pods, containers selected from metric `go_memstats_alloc_bytes`.\n\nBut on this dashboard exists panels in rows `HTTP Statistics` and `HTTP Errors`. These panels will show metrics only if you use `Cloud-Core` go libraries (specifically the library `go-actuator-common`). In other cases panels in these rows will not work."
     }
    }
   ]
  },
  {
   "title": "Quick facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Shows time from VM start",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "description": "Shows VM start time",
   "gridPos": { "h": 3, "w": 7, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} * 1000"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Shows resident memory",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "Shows total threads count in selected area",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(go_threads{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "description": "Shows total routines count in selected area",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(go_goroutines{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "stat",
   "description": "Shows amount of currently opened file descriptors",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_open_fds{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "stat",
   "description": "Show Go version for selected pod and container",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_info{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Memory and GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Process memory",
   "type": "timeseries",
   "description": "Shows resident and virtual memory volume",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "{{pod}}/{{container}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "{{pod}}/{{container}} - virtual"
    }
   ]
  },
  {
   "title": "Process memory / second",
   "type": "timeseries",
   "description": "Shows per-second memory rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[2m])",
     "legendFormat": "{{pod}}/{{container}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[2m])",
     "legendFormat": "{{pod}}/{{container}} - virtual"
    }
   ]
  },
  {
   "title": "Go memstats",
   "type": "timeseries",
   "description": "Shows how much Go is using from the amount of memory the Prometheus process is using from the kernel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "{{pod}}/{{container}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[2m])",
     "legendFormat": "{{pod}}/{{container}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "{{pod}}/{{container}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "{{pod}}/{{container}} - heap inuse"
    }
   ]
  },
  {
   "title": "Go memstats / second",
   "type": "timeseries",
   "description": "Shows per-second rate of how much Go is using from the amount of memory the Prometheus process is using from the kernel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[2m])",
     "legendFormat": "{{pod}}/{{container}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[2m])",
     "legendFormat": "{{pod}}/{{container}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[2m])",
     "legendFormat": "{{pod}}/{{container}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[2m])",
     "legendFormat": "{{pod}}/{{container}} - heap inuse"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Shows the number of goroutined that currently exists",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "timeseries",
   "description": "Shows  the summary of the GC invocation durations",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Open fds",
   "type": "timeseries",
   "description": "Shows the current number of used file descriptors",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Open / closed fds delta",
   "type": "timeseries",
   "description": "Shows delta of used file descriptors. A positive value shows newly opened descriptors, a negative value shows closed descriptors.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(process_open_fds{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[2m])",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HTTP request by code: 2xx or 3xx $pod/$container",
     "type": "timeseries",
     "description": "Shows amount of successful requests to different URLs per second",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(http_request_status{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", status=~\"2..|3..\"}[$__range]) OR on() vector(0)",
       "legendFormat": "{{ path }}: {{ status }}"
      }
     ]
    },
    {
     "title": "95%-tile latency of response time",
     "type": "timeseries",
     "description": "How long it took to process a request, partitioned by method and HTTP path",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \r\n  sum(rate(http_request_time_bucket{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (method,path,le)\r\n)",
       "legendFormat": "method=\"{{method }}\", path=\"{{path}}\" "
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HTTP requests by code: 4xx $pod/$container",
     "type": "timeseries",
     "description": "Shows amount of requests to different URLs per second with code 4xx",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(http_request_status{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", status=~\"4..\"}[$__range]) OR on() vector(0)",
       "legendFormat": "{{ path }}"
      }
     ]
    },
    {
     "title": "HTTP requests by code: 5xx $pod/$container",
     "type": "timeseries",
     "description": "Shows amount of requests to different URLs per second with code 5xx",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(http_request_status{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", status=~\"5..\"}[$__range]) OR on() vector(0)",
       "legendFormat": "{{ path }}"
      }
     ]
    }
   ]
  },
  {
   "title": "GRPC Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Unary requests by OK code",
     "type": "timeseries",
     "description": "Shows amount of successful requests to different methods per second",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\",grpc_type=\"unary\", grpc_code=\"OK\"}[$interval])) by (grpc_code, grpc_method, grpc_service)",
       "legendFormat": "{{grpc_code}}:{{grpc_service}}/{{ grpc_method }}"
      }
     ]
    },
    {
     "title": "Percentage unary requests by OK code",
     "type": "timeseries",
     "description": "Shows percentage of successful requests to different methods per second",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\",grpc_type=\"unary\",grpc_code=\"OK\"}[$interval])) by (grpc_service, grpc_method)\r\n / \r\nsum(rate(grpc_server_started_total{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\",grpc_type=\"unary\"}[$interval])) by (grpc_service, grpc_method)\r\n * 100.0",
       "legendFormat": "{{grpc_service}}/{{ grpc_method }}"
      }
     ]
    },
    {
     "title": "95%-tile latency of unary response time",
     "type": "timeseries",
     "description": "How long it took to process an unary request, partitioned by method",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \r\n  sum(rate(grpc_server_handling_seconds_bucket{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\",grpc_type=\"unary\"}[$interval])) by (grpc_service,grpc_method,le)\r\n) * 1000",
       "legendFormat": "{{grpc_service}}/{{ grpc_method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "GRPC Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Unary failed requests",
     "type": "timeseries",
     "description": "Shows amount of error requests to different methods per second partitioned by error codes",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\",grpc_type=\"unary\", grpc_code!=\"OK\"}[$interval])) by (grpc_code, grpc_method, grpc_service)",
       "legendFormat": "{{grpc_code}}:{{grpc_service}}/{{ grpc_method }}"
      }
     ]
    },
    {
     "title": "Percentage unary failed requests",
     "type": "timeseries",
     "description": "Shows percentage of failed requests to different methods per second",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", grpc_type=\"unary\",grpc_code!=\"OK\"}[$interval])) by ( grpc_service, grpc_method)\r\n / \r\nsum(rate(grpc_server_started_total{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\",grpc_type=\"unary\"}[$interval])) by (grpc_service, grpc_method)\r\n * 100.0",
       "legendFormat": "{{grpc_service}}/{{ grpc_method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open Connections",
     "type": "timeseries",
     "description": "Show count of open SQL connections (statuses: idle, in use)",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(go_sql_stats_connections_in_use{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (db_name) OR on() vector(0)",
       "legendFormat": "In use: {{db_name}}"
      },
      {
       "expr": "sum(go_sql_stats_connections_idle{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (db_name) OR on() vector(0)",
       "legendFormat": "Idle: {{db_name}}"
      }
     ]
    },
    {
     "title": "Blocked Connections",
     "type": "timeseries",
     "description": "Show blocked connections and duration of blocking",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(go_sql_stats_connections_waited_for{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (db_name) OR on() vector(0)",
       "legendFormat": "Waited for: {{db_name}}"
      },
      {
       "expr": "sum(rate(go_sql_stats_connections_blocked_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (db_name) OR on() vector(0)",
       "legendFormat": "Blocking duration: {{db_name}}"
      }
     ]
    },
    {
     "title": "Closed connections",
     "type": "timeseries",
     "description": "Shows number of closed SQL connections by reason",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(go_sql_stats_connections_closed_max_idle{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (db_name) OR on() vector(0)",
       "legendFormat": "Reason - SetMaxIdleConns: {{db_name}}"
      },
      {
       "expr": "sum(increase(go_sql_stats_connections_closed_max_idle_time{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (db_name) OR on() vector(0)",
       "legendFormat": "Reason - SetConnMaxLifetime: {{db_name}}"
      },
      {
       "expr": "sum(increase(go_sql_stats_connections_closed_max_lifetime{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (db_name) OR on() vector(0)",
       "legendFormat": "Reason - SetConnMaxIdleTime: {{db_name}}"
      }
     ]
    }
   ]
  }
 ]
}