{
 "title": "HA Services",
 "description": "This dashboard allows checking whether services in the cluster are running in high availability mode or not",
 "tags": [ "ha" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "How to",
     "type": "text",
     "description": "Describes how to use this dashboard",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# About Dashboard\n\nThis dashboard is designed to identify services that are running in non-HA mode.\n\nIt focused on monitoring of Deployment and StatefulSets, because DaemonSets are running their pods on every node by default.\n\n# High Availability (HA) mode\n\nServices running in HA mode must satisfy the following requirements:\n\n* Have at least 2 available replicas\n* Replicas must be placed on different nodes\n* Replicas must be placed on different availability zones (AZ)\n\nCurrently, this dashboard doesn't have mechanisms for tracking AZ. For these purposes you can use Kubernetes / Pods Distribution By Zones dashboard.\n\n# How to use this dashboard\n\n**NOTE:** If you have a lot of pods and services on the environment, please,\nselect namespaces that you interested in on the `namespace` filter to prevent freezing and crashing of Grafana due to loading a large amount of data.\n\nIf you want to check whether all your services are running in high availability mode,\nfollow the instructions below:\n\n* If `Only 1 replica` number on `Services with Available Replicas` panel is greater than 0:\n  * Check `Desired and Available Replicas` panels for Deployments and StatefulSets\n    * If the controller `Has unavailable replicas`:\n      * Use `Not Healthy Pods` and `Last Terminated Status` panels to identify pods and containers with problems, and try to fix issues\n    * If the controller has `Desired replicas` less than 2:\n      * Check controller's spec and increase `replicas` parameter for it if possible and necessary (it's better to upgrade the service via CMDB rather than change the number directly on the spec)\n* If `Services with Multiple Pods per Node` value is greater than 0:\n  * Check all `Multiple Replicas on the Same Node` panels, and if the panel has data:\n    * Unfortunately, there is no a proper way to distribute replicas across nodes, but you can read [this article in the official documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) to avoid such situations as mush as possible\n"
     }
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Services with Available Replicas",
   "type": "stat",
   "description": "Shows total number of services (Deployments and StatefulSets) with at least 1 available replica, number of services with only 1 available replica (non-HA mode) and with 2 or more replicas (HA mode)",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(kube_deployment_status_replicas_available{cluster=\"$cluster\", namespace=~\"$namespace\"} > 0) OR on() vector(0)) + (count(kube_statefulset_status_replicas_available{cluster=\"$cluster\", namespace=~\"$namespace\"} > 0) OR on() vector(0))",
     "legendFormat": "Total"
    },
    {
     "expr": "(count(kube_deployment_status_replicas_available{cluster=\"$cluster\", namespace=~\"$namespace\"} == 1) OR on() vector(0)) + (count(kube_statefulset_status_replicas_available{cluster=\"$cluster\", namespace=~\"$namespace\"} == 1) OR on() vector(0))",
     "legendFormat": "Only 1 replica"
    },
    {
     "expr": "(count(kube_deployment_status_replicas_available{cluster=\"$cluster\", namespace=~\"$namespace\"} > 1) OR on() vector(0)) + (count(kube_statefulset_status_replicas_available{cluster=\"$cluster\", namespace=~\"$namespace\"} > 1) OR on() vector(0))",
     "legendFormat": "2 or more replicas"
    }
   ]
  },
  {
   "title": "Services with Unavailable Replicas",
   "type": "stat",
   "description": "Total number of services (Deployments and StatefulSets) with unavailable replicas",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((count(kube_deployment_status_replicas_available{cluster=\"$cluster\", namespace=~\"$namespace\"} < kube_deployment_status_replicas{cluster=\"$cluster\", namespace=~\"$namespace\"}) >= 0)  OR on() vector(0)) + ((count(kube_statefulset_status_replicas_available{cluster=\"$cluster\", namespace=~\"$namespace\"} < kube_statefulset_status_replicas{cluster=\"$cluster\", namespace=~\"$namespace\"}) >= 0)  OR on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services with Multiple Pods per Node",
   "type": "stat",
   "description": "Total number of services (Deployments and StatefulSets) with 2 or more pods placed on the same node",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\", node=~\".+\", created_by_kind=~\"ReplicaSet|StatefulSet\"}) by (namespace, node, created_by_name) > 1) >= 0 OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Replicas",
   "type": "stat",
   "description": "Shows number of pods controlled by Deployments and StatefulSets",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (phase)\r\n(\r\n(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"} * on (cluster, namespace, pod) group_left(phase) (kube_pod_status_phase{cluster=\"$cluster\", namespace=~\"$namespace\"} == 1))\r\n * on (namespace, pod) group_left()\r\nkube_pod_owner{cluster=\"$cluster\", namespace=~\"$namespace\", owner_kind=~\"ReplicaSet|StatefulSet\"}\r\n)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Desired and Available Replicas",
     "type": "table",
     "description": "Shows number of available and desired replicas for every Deployment\n\nServices in HA mode must have more than 1 available replicas",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{cluster=\"$cluster\", namespace=~\"$namespace\"}) by (deployment, namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_available{cluster=\"$cluster\", namespace=~\"$namespace\"}) by (deployment, namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_available{cluster=\"$cluster\", namespace=~\"$namespace\"} < kube_deployment_status_replicas{cluster=\"$cluster\", namespace=~\"$namespace\"}) by (deployment, namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Multiple Replicas on the Same Node",
     "type": "table",
     "description": "Shows Deployments if 2 or more their replicas placed on the same node\n\nServices are not allowed to have 2 or more replicas on the same node in HA mode",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "count(label_replace((kube_pod_info{cluster=\"$cluster\", node=~\".+\", namespace=~\"$namespace\"} == 1) * on(pod, namespace) group_left(owner_name) kube_pod_owner{cluster=\"$cluster\", namespace=~\"$namespace\", owner_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") * on(replicaset, namespace) group_left(owner_name) kube_replicaset_owner{cluster=\"$cluster\", namespace=~\"$namespace\"}) by (namespace, owner_name, node) > 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Not Healthy Pods",
     "type": "table",
     "description": "Show information about the reason the container is currently in waiting or terminated state for pods controlled by Deployments",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "label_replace((kube_pod_container_status_waiting_reason{cluster=\"$cluster\", namespace=~\"$namespace\"} == 1) * on(pod, namespace) group_left(owner_name) kube_pod_owner{cluster=\"$cluster\", namespace=~\"$namespace\", owner_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") * on(replicaset, namespace) group_left(owner_name) kube_replicaset_owner{cluster=\"$cluster\", namespace=~\"$namespace\"}"
      },
      {
       "expr": "label_replace((kube_pod_container_status_terminated_reason{cluster=\"$cluster\", namespace=~\"$namespace\",reason!=\"Completed\"} == 1) * on(pod, namespace) group_left(owner_name) kube_pod_owner{cluster=\"$cluster\", namespace=~\"$namespace\", owner_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") * on(replicaset, namespace) group_left(owner_name) kube_replicaset_owner{cluster=\"$cluster\", namespace=~\"$namespace\"}"
      },
      {
       "expr": "label_replace((label_replace(kube_pod_status_phase{cluster=\"$cluster\", namespace=~\"$namespace\", phase=\"Pending\"}, \"reason\", \"$1\", \"phase\", \"(.*)\") == 1) * on(pod, namespace) group_left(owner_name) kube_pod_owner{cluster=\"$cluster\", namespace=~\"$namespace\", owner_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") * on(replicaset, namespace) group_left(owner_name) kube_replicaset_owner{cluster=\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Last Terminated Status",
     "type": "table",
     "description": "Show information about the last reason the container was in terminated state for pods controlled by Deployments",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "label_replace((kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", namespace=~\"$namespace\", reason!=\"Completed\"} == 1) * on(pod, namespace) group_left(owner_name) kube_pod_owner{cluster=\"$cluster\", namespace=~\"$namespace\", owner_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") * on(replicaset, namespace) group_left(owner_name) kube_replicaset_owner{cluster=\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "{{exported_pod}}-{{exported_namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "StatefulSets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Desired and Available Replicas",
     "type": "table",
     "description": "Shows number of available and desired replicas for every StatefulSet\n\nServices in HA mode must have more than 1 available replicas",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(kube_statefulset_status_replicas{cluster=\"$cluster\", namespace=~\"$namespace\"}) by (statefulset, namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(kube_statefulset_status_replicas_available{cluster=\"$cluster\", namespace=~\"$namespace\"}) by (statefulset, namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(kube_statefulset_status_replicas_available{cluster=\"$cluster\", namespace=~\"$namespace\"} < kube_statefulset_status_replicas{cluster=\"$cluster\", namespace=~\"$namespace\"}) by (statefulset, namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Multiple Replicas on the Same Node",
     "type": "table",
     "description": "Shows StatefulSets if 2 or more their replicas placed on the same node\n\nServices are not allowed to have 2 or more replicas on the same node in HA mode",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "count((kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"} == 1) * on(pod, namespace) group_left(owner_name) kube_pod_owner{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_kind=\"StatefulSet\"}) by (namespace, owner_name, node) > 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Not Healthy Pods",
     "type": "table",
     "description": "Show information about the reason the container is currently in waiting or terminated state for pods controlled by StatefulSets",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "(kube_pod_container_status_waiting_reason{cluster=\"$cluster\", namespace=~\"$namespace\"} == 1) * on(pod, namespace) group_left(owner_name) kube_pod_owner{cluster=\"$cluster\", namespace=~\"$namespace\", owner_kind=\"StatefulSet\"}"
      },
      {
       "expr": "(kube_pod_container_status_terminated_reason{cluster=\"$cluster\", namespace=~\"$namespace\",reason!=\"Completed\"} == 1) * on(pod, namespace) group_left(owner_name) kube_pod_owner{cluster=\"$cluster\", namespace=~\"$namespace\", owner_kind=\"StatefulSet\"}"
      },
      {
       "expr": "(label_replace(kube_pod_status_phase{cluster=\"$cluster\", namespace=~\"$namespace\", phase=\"Pending\"}, \"reason\", \"$1\", \"phase\", \"(.*)\") == 1) * on(pod, namespace) group_left(owner_name) kube_pod_owner{cluster=\"$cluster\", namespace=~\"$namespace\", owner_kind=\"StatefulSet\"}"
      }
     ]
    },
    {
     "title": "Last Terminated Status",
     "type": "table",
     "description": "Show information about the last reason the container was in terminated state for pods controlled by StatefulSets",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "(kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", namespace=~\"$namespace\", reason!=\"Completed\"} == 1) * on(pod, namespace) group_left(owner_name) kube_pod_owner{cluster=\"$cluster\", namespace=~\"$namespace\", owner_kind=\"StatefulSet\"}",
       "legendFormat": "{{exported_pod}}-{{exported_namespace}}"
      }
     ]
    }
   ]
  }
 ]
}