{
 "title": "Home Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "prometheus_instance",
    "query": {
     "query": "label_values(prometheus_build_info, instance)"
    }
   },
   {
    "name": "alertmanager_instance",
    "query": {
     "query": "label_values(alertmanager_build_info, instance)"
    }
   },
   { "name": "interval", "query": "5m" },
   {
    "name": "prometheus_namespace",
    "query": {
     "query": "label_values(prometheus_build_info, namespace)"
    }
   },
   {
    "name": "kuber_dashboard",
    "query": {
     "query": "label_values(kube_ingress_path{ingress=~\"kubernetes-dashboard\"}, host)"
    }
   },
   {
    "name": "prometheus_UI",
    "query": {
     "query": "label_values(kube_ingress_path{exported_namespace=\"$prometheus_namespace\",service_port=\"9090\"}, host)"
    }
   },
   {
    "name": "alertmanager_UI",
    "query": {
     "query": "label_values(kube_ingress_path{exported_namespace=\"$prometheus_namespace\",service_port=\"9093\"}, host)"
    }
   },
   {
    "name": "vm_instance",
    "query": {
     "query": "label_values(vm_app_version{container=\"vmagent\"}, instance)"
    }
   },
   {
    "name": "vm_namespace",
    "query": {
     "query": "label_values(vm_app_version, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "&nbsp;\n\n\n### This page displayed [Prometheus](https://$prometheus_UI) and [Alertmanager](https://$alertmanager_UI) status, Ready pods and the Total number of pods in the Monitoring namespace. \n\n### Dashboards are grouped by tags on next panels:\n#### - Self-Monitoring Dashboard\n#### - Favorites Dashboards (your favorites dashboards)\n#### - Kubernetes Dashboards (dashboards with tag: \"k8s\")\n#### - Services Dashboards (kafka, postgresql, mongodb, etc; tag: \"prometheus\")\n#### - Standalone Hosts Dashboards (Graylog, balancers, etc; tag: \"standalone\")\n\n### [Link to Kubernetes Dashboard](https://$kuber_dashboard)\n\n\n"
   }
  },
  {
   "title": "Monitoring Uptime",
   "type": "stat",
   "description": "Show the prometheus instance uptime",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(time() - process_start_time_seconds{instance=~\"$prometheus_instance\"}) by(instance)"
    },
    {
     "expr": "max(time() - process_start_time_seconds{instance=~\"$vm_instance\"}) by(instance)"
    }
   ]
  },
  {
   "title": "Uptime Alertmanager",
   "type": "stat",
   "description": "Show the alertmanager instance uptime",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(time() - process_start_time_seconds{instance=\"$alertmanager_instance\"}) by(instance)"
    }
   ]
  },
  {
   "title": "Ready pods / All pods",
   "type": "stat",
   "description": "Show Ready pods and all pods in the monitoring namespace",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{exported_namespace=\"$prometheus_namespace\", condition=\"true\"})"
    },
    {
     "expr": "sum(kube_pod_status_ready{exported_namespace=\"$prometheus_namespace\"})"
    },
    {
     "expr": "sum(kube_pod_status_ready{exported_namespace=\"$vm_namespace\", condition=\"true\"})"
    },
    {
     "expr": "sum(kube_pod_status_ready{exported_namespace=\"$vm_namespace\"})"
    }
   ]
  },
  {
   "title": "Services",
   "type": "dashlist",
   "description": "Show dashboards with \"prometheus\" tag",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 8 }
  },
  { "title": "All dashboards", "type": "dashlist", "description": "Show all dashboards", "gridPos": { "h": 17, "w": 8, "x": 16, "y": 8 } },
  { "type": "dashlist", "gridPos": { "h": 2, "w": 9, "x": 0, "y": 11 } },
  { "title": "Favorite", "type": "dashlist", "description": "Show your favorite dashboards", "gridPos": { "h": 6, "w": 9, "x": 0, "y": 13 } },
  {
   "title": "Standalone hosts",
   "type": "dashlist",
   "description": "Show dashboard with \"standalone\" tag",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 17 }
  },
  {
   "title": "Kubernetes",
   "type": "dashlist",
   "description": "Show dashboards with \"k8s\" tag",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 19 }
  }
 ]
}