{
 "title": "Ingress / Nginx controller",
 "description": "Ingress-nginx supports a rich collection of prometheus metrics. If you have prometheus and grafana installed on your cluster then prometheus will already be scraping this data due to the scrape annotation on the deployment.",
 "tags": [
  "k8s",
  "ingress",
  "nginx"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values( nginx_ingress_controller_requests, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_ingress_created{cluster=~\"$cluster\"}, exported_namespace)"
    }
   },
   {
    "name": "controller_class",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster=~\"$cluster\", namespace=~\"$controller_namespace\"}, controller_class) "
    }
   },
   {
    "name": "controller_namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster=~\"$cluster\"}, controller_namespace)"
    }
   },
   {
    "name": "ingress",
    "query": {
     "query": "label_values(kube_ingress_created{cluster=~\"$cluster\",exported_namespace=~\"$namespace\"}, ingress)"
    }
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster=~\"$cluster\",namespace=~\"$controller_namespace\",controller_class=~\"$controller_class\"}, controller_pod) "
    }
   },
   {
    "name": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Controller Request Volume",
   "type": "stat",
   "description": "Show number of requests per second",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",ingress=~\"$ingress\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$controller_namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "stat",
   "description": "Show average number of client connection",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{cluster=~\"$cluster\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$controller_namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "Controller Success Rate (non-4|5xx responses)",
   "type": "stat",
   "description": "Show percentage successfully requests",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$controller_namespace\",ingress=~\"$ingress\",status!~\"[4-5].*\"}[2m])) / sum(rate(nginx_ingress_controller_requests{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",ingress=~\"$ingress\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$controller_namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "stat",
   "description": "Show number of Ingress controller reload operations",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_success{cluster=~\"$cluster\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$controller_namespace\"})"
    }
   ]
  },
  {
   "title": "Last Config Failed",
   "type": "stat",
   "description": "Shows that last configuration failed",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(nginx_ingress_controller_config_last_reload_successful{cluster=~\"$cluster\",controller_pod=~\"$controller\",controller_namespace=~\"$controller_namespace\"} == 0)"
    }
   ]
  },
  {
   "title": "Ingress Request Volume",
   "type": "timeseries",
   "description": "Show the total number of client requests by ingress",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",ingress=~\"$ingress\",controller_namespace=~\"$controller_namespace\",ingress=~\"$ingress\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "timeseries",
   "description": "Show percentage successfully requests by ingress",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$controller_namespace\",ingress=~\"$ingress\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$controller_namespace\",ingress=~\"$ingress\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "description": "Show request size (including request line, header, and request body)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (irate (nginx_ingress_controller_request_size_sum{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\", ingress=~\"$ingress\",controller_namespace=~\"$controller_namespace\"}[2m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (irate (nginx_ingress_controller_response_size_sum{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",ingress=~\"$ingress\",controller_namespace=~\"$controller_namespace\"}[2m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Show the number of bytes of memory in use ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_nginx_process_resident_memory_bytes{cluster=~\"$cluster\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$controller_namespace\"}) by (controller_pod)",
     "legendFormat": "{{ controller_pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Show cpu usage ",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate (nginx_ingress_controller_nginx_process_cpu_seconds_total{cluster=~\"$cluster\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$controller_namespace\"}[2m])) by (controller_pod)",
     "legendFormat": "{{controller_pod }}"
    }
   ]
  },
  {
   "title": "Ingress Percentile Response Times and Transfer Rates",
   "type": "table",
   "description": "Show the requests processing time in milliseconds (le = 0.5, 09, 0.99) an requests size by ingress",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$controller_namespace\",ingress=~\"$ingress\"}[2m])) by (le, ingress, exported_namespace))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$controller_namespace\",ingress=~\"$ingress\"}[2m])) by (le, ingress, exported_namespace))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$controller_namespace\",ingress=~\"$ingress\"}[2m])) by (le, ingress, exported_namespace))",
     "legendFormat": "{{ destination_service }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_request_size_sum{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$controller_namespace\",ingress=~\"$ingress\"}[2m])) by (ingress, exported_namespace)",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_response_size_sum{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$controller_namespace\",ingress=~\"$ingress\"}[2m])) by (ingress, exported_namespace)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Certificate Expiry",
   "type": "table",
   "description": "Shows time until the SSL Certificate expires",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_ssl_expire_time_seconds{cluster=~\"$cluster\",pod=~\"$controller\",namespace=~\"$controller_namespace\",ingress=~\"$ingress\"}) by (host, pod) - time()"
    }
   ]
  }
 ]
}