{
 "title": "Ingress / Request Handling Performance",
 "tags": [
  "k8s",
  "ingress",
  "nginx"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(nginx_ingress_controller_success, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_request_duration_seconds_bucket{cluster=~\"$cluster\"}, exported_namespace)"
    }
   },
   {
    "name": "ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{cluster=~\"$cluster\", exported_namespace=~\"$namespace\"}, ingress)"
    }
   },
   {
    "name": "interval",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total request handling time",
   "type": "timeseries",
   "description": "Total time taken for nginx and upstream servers to process a request and send a response",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        cluster=~\"$cluster\",exported_namespace=~\"$namespace\",ingress =~ \"$ingress\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "quantile = 5"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n    nginx_ingress_controller_request_duration_seconds_bucket{\n        cluster=~\"$cluster\",exported_namespace=~\"$namespace\",ingress =~ \"$ingress\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "quantile = 95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        cluster=~\"$cluster\", exported_namespace=~\"$namespace\", ingress =~ \"$ingress\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "quantile = 99"
    }
   ]
  },
  {
   "title": "Upstream response time",
   "type": "timeseries",
   "description": "The time spent on receiving the response from the upstream server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_response_duration_seconds_bucket{\n        cluster=~\"$cluster\",exported_namespace=~\"$namespace\",ingress =~ \"$ingress\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "quantile = 5"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n    nginx_ingress_controller_response_duration_seconds_bucket{\n        cluster=~\"$cluster\",exported_namespace=~\"$namespace\",ingress =~ \"$ingress\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "quantile = 95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_response_duration_seconds_bucket{\n        cluster=~\"$cluster\",exported_namespace=~\"$namespace\",ingress =~ \"$ingress\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "quantile = 99"
    }
   ]
  },
  {
   "title": "Request volume by Path",
   "type": "timeseries",
   "description": "Shows requests per second, group by path",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "  sum by (path)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_count{\n        cluster=~\"$cluster\",exported_namespace=~\"$namespace\",ingress =~ \"$ingress\"\n      }[2m]\n    )\n  )\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Median upstream response time by Path",
   "type": "timeseries",
   "description": "For each path observed, its median upstream response time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  .5,\n  sum by (le, path)(\n    rate(\n      nginx_ingress_controller_response_duration_seconds_bucket{\n        cluster=~\"$cluster\", exported_namespace=~\"$namespace\", ingress =~ \"$ingress\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Response error rate by Path",
   "type": "timeseries",
   "description": "Percentage of 4xx and 5xx responses among all responses.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(nginx_ingress_controller_request_duration_seconds_count{\n  cluster =~ \"$cluster\",\n  exported_namespace =~ \"$namespace\",\n  ingress =~ \"$ingress\",\n  status =~ \"[4-5].*\"\n}[2m])) / sum by (path) (rate(nginx_ingress_controller_request_duration_seconds_count{\n  ingress =~ \"$ingress\",\n}[2m]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Upstream time consumed by Path",
   "type": "timeseries",
   "description": "For each path observed, the sum of upstream request time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(nginx_ingress_controller_response_duration_seconds_sum{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",ingress =~ \"$ingress\"}[2m]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Response error volume by Path",
   "type": "timeseries",
   "description": "Show request errors with 4xx, 5xx codes by path",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "  sum (\n    rate(\n      nginx_ingress_controller_request_duration_seconds_count{\n        cluster =~ \"$cluster\",\n        exported_namespace =~ \"$namespace\",\n        ingress =~ \"$ingress\",\n        status =~\"[4-5].*\",\n      }[2m]\n    )\n  ) by(path, status)\n",
     "legendFormat": "{{ path }} {{ status }}"
    }
   ]
  },
  {
   "title": "Average response size by Path",
   "type": "timeseries",
   "description": "Show average response size by path",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (\n  rate (\n      nginx_ingress_controller_response_size_sum {\n        cluster =~ \"$cluster\",\n        exported_namespace =~ \"$namespace\",\n        ingress =~ \"$ingress\",\n      }[2m]\n  )\n)  by (path) / sum (\n  rate(\n      nginx_ingress_controller_response_size_count {\n        cluster =~ \"$cluster\",\n        exported_namespace =~ \"$namespace\",\n        ingress =~ \"$ingress\",\n      }[2m]\n  )\n) by (path)\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Upstream service latency",
   "type": "timeseries",
   "description": "Show average upstream service latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (\n  rate(\n      nginx_ingress_controller_ingress_upstream_latency_seconds_sum {\n        cluster =~ \"$cluster\",\n        exported_namespace =~ \"$namespace\",\n        ingress =~ \"$ingress\",\n      }[2m]\n)) / sum (\n  rate(\n      nginx_ingress_controller_ingress_upstream_latency_seconds_count {\n        cluster =~ \"$cluster\",\n        exported_namespace =~ \"$namespace\",\n        ingress =~ \"$ingress\",\n      }[2m]\n  )\n)\n",
     "legendFormat": "average"
    }
   ]
  }
 ]
}