{
 "title": "Kubernetes / Distribution by Labels",
 "description": "The dashboard allows filtering Kubernetes resources (pods, ingresses, etc.) by app.kubernetes.io labels",
 "tags": [
  "k8s",
  "labels"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up,cluster)" } },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(kube_pod_labels{cluster=\"$cluster\", namespace=~\"$namespace\"},label_app_kubernetes_io_name)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kube_pod_labels{cluster=\"$cluster\", namespace=~\"$namespace\"},label_app_kubernetes_io_instance)"
    }
   },
   {
    "name": "version",
    "label": "version",
    "query": {
     "query": "label_values(kube_pod_labels{cluster=\"$cluster\", namespace=~\"$namespace\"},label_app_kubernetes_io_version)"
    }
   },
   {
    "name": "component",
    "label": "component",
    "query": {
     "query": "label_values(kube_pod_labels{cluster=\"$cluster\", namespace=~\"$namespace\"},label_app_kubernetes_io_component)"
    }
   },
   {
    "name": "partOf",
    "label": "part-of",
    "query": {
     "query": "label_values(kube_pod_labels{cluster=\"$cluster\", namespace=~\"$namespace\"},label_app_kubernetes_io_part_of)"
    }
   },
   {
    "name": "managedBy",
    "label": "managed-by",
    "query": {
     "query": "label_values(kube_pod_labels{cluster=\"$cluster\", namespace=~\"$namespace\"},label_app_kubernetes_io_managed_by)"
    }
   },
   {
    "name": "managedByOperator",
    "label": "managed-by-operator",
    "query": {
     "query": "label_values(kube_pod_labels{cluster=\"$cluster\", namespace=~\"$namespace\"},label_app_kubernetes_io_managed_by_operator)"
    }
   },
   {
    "name": "technology",
    "label": "technology",
    "query": {
     "query": "label_values(kube_pod_labels{cluster=\"$cluster\", namespace=~\"$namespace\"},label_app_kubernetes_io_technology)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "💡Help",
     "type": "text",
     "description": "Shows information about current dashboard",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# Distribution by Labels\n\nThis dashboards shows Pods, Ingresses, Deployments (with ReplicaSets), StatefulSets, DaemonSets and Jobs with associated `app.kubernetes.io` labels:\n\n* app.kubernetes.io/name\n* app.kubernetes.io/instance\n* app.kubernetes.io/version\n* app.kubernetes.io/component\n* app.kubernetes.io/part-of\n* app.kubernetes.io/managed-by\n* app.kubernetes.io/managed-by-operator\n* app.kubernetes.io/technology\n\nYou can filter out values in tables by using the filter icon next to the column name for each column. Notice that you can filter out even blanc values in this case.\n\nDashboard filters on the top of the dashboard also can be used for this purpose, but keep in mind that values for these filters are taken from `kube_pod_labels` metric. Therefore, label values that are not contained in at least one of the pods will not be included in these filters.\n\n**IMPORTANT NOTE ABOUT DEPLOYMENTS:** Table `Deployments and ReplicaSets` shows information only about deployments and replicasets that currently have more than 0 ready replicas."
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods",
     "type": "table",
     "description": "Shows pods with associated app.kubernetes.io labels",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "group (\r\n  kube_pod_labels{cluster=\"$cluster\", namespace=~\"$namespace\", label_app_kubernetes_io_name=~\"$name\", label_app_kubernetes_io_instance=~\"$instance\", label_app_kubernetes_io_version=~\"$version\", label_app_kubernetes_io_component=~\"$component\", label_app_kubernetes_io_part_of=~\"$partOf\", label_app_kubernetes_io_managed_by=~\"$managedBy\", label_app_kubernetes_io_managed_by_operator=~\"$managedByOperator\", label_app_kubernetes_io_technology=~\"$technology\"}\r\n)\r\nby (namespace, pod, label_app_kubernetes_io_name, label_app_kubernetes_io_instance, label_app_kubernetes_io_version, label_app_kubernetes_io_component, label_app_kubernetes_io_part_of, label_app_kubernetes_io_managed_by, label_app_kubernetes_io_managed_by_operator, label_app_kubernetes_io_technology)\r\n*\r\non (namespace, pod)\r\ngroup_right(label_app_kubernetes_io_name, label_app_kubernetes_io_instance, label_app_kubernetes_io_version, label_app_kubernetes_io_component, label_app_kubernetes_io_part_of, label_app_kubernetes_io_managed_by, label_app_kubernetes_io_managed_by_operator, label_app_kubernetes_io_technology)\r\n  (\r\n    group (\r\n      kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}\r\n    )\r\n    by (namespace, pod)\r\n  )"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingresses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingresses",
     "type": "table",
     "description": "Shows ingresses with associated app.kubernetes.io labels",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "group (\r\n  kube_ingress_labels{cluster=\"$cluster\", namespace=~\"$namespace\", label_app_kubernetes_io_name=~\"$name\", label_app_kubernetes_io_instance=~\"$instance\", label_app_kubernetes_io_version=~\"$version\", label_app_kubernetes_io_component=~\"$component\", label_app_kubernetes_io_part_of=~\"$partOf\", label_app_kubernetes_io_managed_by=~\"$managedBy\", label_app_kubernetes_io_managed_by_operator=~\"$managedByOperator\", label_app_kubernetes_io_technology=~\"$technology\"}\r\n)\r\nby (namespace, ingress, label_app_kubernetes_io_name, label_app_kubernetes_io_instance, label_app_kubernetes_io_version, label_app_kubernetes_io_component, label_app_kubernetes_io_part_of, label_app_kubernetes_io_managed_by, label_app_kubernetes_io_managed_by_operator, label_app_kubernetes_io_technology)\r\n*\r\non (namespace, ingress)\r\ngroup_right(label_app_kubernetes_io_name, label_app_kubernetes_io_instance, label_app_kubernetes_io_version, label_app_kubernetes_io_component, label_app_kubernetes_io_part_of, label_app_kubernetes_io_managed_by, label_app_kubernetes_io_managed_by_operator, label_app_kubernetes_io_technology)\r\n  (\r\n    group (\r\n      kube_ingress_path{cluster=\"$cluster\", namespace=~\"$namespace\"}\r\n    )\r\n    by (namespace, ingress, host)\r\n  )"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployments and ReplicaSets",
     "type": "table",
     "description": "Shows deployments and replicasets with associated app.kubernetes.io labels, if they have more than 0 ready replicas",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "group (\r\n  kube_deployment_labels{cluster=\"$cluster\", namespace=~\"$namespace\", label_app_kubernetes_io_name=~\"$name\", label_app_kubernetes_io_instance=~\"$instance\", label_app_kubernetes_io_version=~\"$version\", label_app_kubernetes_io_component=~\"$component\", label_app_kubernetes_io_part_of=~\"$partOf\", label_app_kubernetes_io_managed_by=~\"$managedBy\", label_app_kubernetes_io_managed_by_operator=~\"$managedByOperator\", label_app_kubernetes_io_technology=~\"$technology\"}\r\n)\r\nby (namespace, deployment, label_app_kubernetes_io_name, label_app_kubernetes_io_instance, label_app_kubernetes_io_version, label_app_kubernetes_io_component, label_app_kubernetes_io_part_of, label_app_kubernetes_io_managed_by, label_app_kubernetes_io_managed_by_operator, label_app_kubernetes_io_technology)\r\n* \r\non (namespace, deployment) \r\ngroup_left(replicaset)\r\n  group(\r\n    kube_deployment_status_replicas_ready{cluster=\"$cluster\", namespace=~\"$namespace\"} \r\n    == \r\n    on(namespace, deployment) \r\n    group_left(replicaset)\r\n      label_replace(\r\n        group(\r\n          kube_replicaset_status_ready_replicas{cluster=\"$cluster\", namespace=~\"$namespace\"} > 0\r\n        ) \r\n        by (namespace, replicaset, owner_name)\r\n        * \r\n        on(namespace, replicaset) \r\n        group_left(owner_name)\r\n          group(\r\n            kube_replicaset_owner{cluster=\"$cluster\", namespace=~\"$namespace\", owner_kind=\"Deployment\"}\r\n          )\r\n          by (namespace, replicaset, owner_name)\r\n      , \"deployment\", \"$1\", \"owner_name\",\"(.*)\")\r\n  )\r\n  by (namespace, deployment, replicaset)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "StatefulSets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "StatefulSets",
     "type": "table",
     "description": "Shows statefulsets with associated app.kubernetes.io labels",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "group (\r\n  kube_statefulset_labels{cluster=\"$cluster\", namespace=~\"$namespace\", label_app_kubernetes_io_name=~\"$name\", label_app_kubernetes_io_instance=~\"$instance\", label_app_kubernetes_io_version=~\"$version\", label_app_kubernetes_io_component=~\"$component\", label_app_kubernetes_io_part_of=~\"$partOf\", label_app_kubernetes_io_managed_by=~\"$managedBy\", label_app_kubernetes_io_managed_by_operator=~\"$managedByOperator\", label_app_kubernetes_io_technology=~\"$technology\"}\r\n)\r\nby (namespace, statefulset, label_app_kubernetes_io_name, label_app_kubernetes_io_instance, label_app_kubernetes_io_version, label_app_kubernetes_io_component, label_app_kubernetes_io_part_of, label_app_kubernetes_io_managed_by, label_app_kubernetes_io_managed_by_operator, label_app_kubernetes_io_technology)\r\n*\r\non (namespace, statefulset)\r\ngroup_right(label_app_kubernetes_io_name, label_app_kubernetes_io_instance, label_app_kubernetes_io_version, label_app_kubernetes_io_component, label_app_kubernetes_io_part_of, label_app_kubernetes_io_managed_by, label_app_kubernetes_io_managed_by_operator, label_app_kubernetes_io_technology)\r\n  (\r\n    group (\r\n      kube_statefulset_created{cluster=\"$cluster\", namespace=~\"$namespace\"}\r\n    )\r\n    by (namespace, statefulset)\r\n  )",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "DaemonSets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "DaemonSets",
     "type": "table",
     "description": "Shows daemonsets with associated app.kubernetes.io labels",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "group (\r\n  kube_daemonset_labels{cluster=\"$cluster\", namespace=~\"$namespace\", label_app_kubernetes_io_name=~\"$name\", label_app_kubernetes_io_instance=~\"$instance\", label_app_kubernetes_io_version=~\"$version\", label_app_kubernetes_io_component=~\"$component\", label_app_kubernetes_io_part_of=~\"$partOf\", label_app_kubernetes_io_managed_by=~\"$managedBy\", label_app_kubernetes_io_managed_by_operator=~\"$managedByOperator\", label_app_kubernetes_io_technology=~\"$technology\"}\r\n)\r\nby (namespace, daemonset, label_app_kubernetes_io_name, label_app_kubernetes_io_instance, label_app_kubernetes_io_version, label_app_kubernetes_io_component, label_app_kubernetes_io_part_of, label_app_kubernetes_io_managed_by, label_app_kubernetes_io_managed_by_operator, label_app_kubernetes_io_technology)\r\n*\r\non (namespace, daemonset)\r\ngroup_right(label_app_kubernetes_io_name, label_app_kubernetes_io_instance, label_app_kubernetes_io_version, label_app_kubernetes_io_component, label_app_kubernetes_io_part_of, label_app_kubernetes_io_managed_by, label_app_kubernetes_io_managed_by_operator, label_app_kubernetes_io_technology)\r\n  (\r\n    group (\r\n      kube_daemonset_created{cluster=\"$cluster\", namespace=~\"$namespace\"}\r\n    )\r\n    by (namespace, daemonset)\r\n  )",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs",
     "type": "table",
     "description": "Shows Kubernetes jobs with associated app.kubernetes.io labels",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "group (\r\n  kube_job_labels{cluster=\"$cluster\", namespace=~\"$namespace\", label_app_kubernetes_io_name=~\"$name\", label_app_kubernetes_io_instance=~\"$instance\", label_app_kubernetes_io_version=~\"$version\", label_app_kubernetes_io_component=~\"$component\", label_app_kubernetes_io_part_of=~\"$partOf\", label_app_kubernetes_io_managed_by=~\"$managedBy\", label_app_kubernetes_io_managed_by_operator=~\"$managedByOperator\", label_app_kubernetes_io_technology=~\"$technology\"}\r\n)\r\nby (namespace, job_name, label_app_kubernetes_io_name, label_app_kubernetes_io_instance, label_app_kubernetes_io_version, label_app_kubernetes_io_component, label_app_kubernetes_io_part_of, label_app_kubernetes_io_managed_by, label_app_kubernetes_io_managed_by_operator, label_app_kubernetes_io_technology)\r\n*\r\non (namespace, job_name)\r\ngroup_right(label_app_kubernetes_io_name, label_app_kubernetes_io_instance, label_app_kubernetes_io_version, label_app_kubernetes_io_component, label_app_kubernetes_io_part_of, label_app_kubernetes_io_managed_by, label_app_kubernetes_io_managed_by_operator, label_app_kubernetes_io_technology)\r\n  (\r\n    group (\r\n      kube_job_created{cluster=\"$cluster\", namespace=~\"$namespace\"}\r\n    )\r\n    by (namespace, job_name)\r\n  )"
      }
     ]
    }
   ]
  }
 ]
}