{
 "title": "Openshift / Cluster version operator",
 "description": "Dashboards shows Cluster version operator specific metrics",
 "tags": [
  "openshift",
  "cluster-version-operator"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "interval",
    "query": "30s,1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Openshift / Cluster version operator",
     "type": "text",
     "description": "Describes some specific use cases for panels",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# This dashboard is designed for Openshift 4.5 and higher\n\n* Platform monitoring is adapted to collect metrics from Openshift 4.5 and higher.\n* Please note, panels don't work in OpenShift v3.11.\n* Please make sure that cluster version operator is deployed and started. Otherwise metrics won't be shown."
     }
    }
   ]
  },
  { "title": "Cluster version overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Operator status",
   "type": "stat",
   "description": "Shows cluster version operator status",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_installer{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current version",
   "type": "stat",
   "description": "Shows current version of the cluster",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_version{cluster=\"$cluster\", type=\"cluster\"}",
     "legendFormat": "{{version }}"
    }
   ]
  },
  {
   "title": "Updated version",
   "type": "stat",
   "description": "Shows version from which current was updated",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_version{cluster=\"$cluster\", type=\"cluster\"}",
     "legendFormat": "{{from_version}}"
    }
   ]
  },
  {
   "title": "Initial version of cluster",
   "type": "stat",
   "description": "Shows initial version of the cluster",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_installer{cluster=\"$cluster\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Payload",
   "type": "timeseries",
   "description": "Shows statistics about applied, pending and errors",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "rate(cluster_version_payload{cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "rate(cluster_operator_payload_errors{cluster=\"$cluster\"}[5m])",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Cluster version capability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cluster capabilities",
     "type": "table",
     "description": "Shows currently enabled cluster capabilities",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum by (name) (cluster_version_capability{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster operators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cluster operators status",
     "type": "table",
     "description": "Shows cluster operators status by  reason",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "cluster_operator_up{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Available  cluster operators",
     "type": "table",
     "description": "Available  cluster operators by reason",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "cluster_operator_conditions{cluster=\"$cluster\", condition=\"Available\"} == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Degraded  cluster operators",
     "type": "table",
     "description": "Degraded cluster operators by reason",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "cluster_operator_conditions{cluster=\"$cluster\", condition=\"Degraded\"} == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Upgradeable  cluster operators",
     "type": "table",
     "description": "Shows cluster operators which can be upgraded by reason",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "cluster_operator_conditions{cluster=\"$cluster\", condition=\"Upgradeable\"} == 1",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Go stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "Shows the CPU usage by cluster version operator",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"cluster-version-operator\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "description": "Shows the number of goroutines for cluster version operator",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"cluster-version-operator\", cluster=\"$cluster\"} ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Resident memory",
     "type": "timeseries",
     "description": "Show the resident memory usage by cluster version operator",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"cluster-version-operator\", cluster=\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Allocated memory",
     "type": "timeseries",
     "description": "Shows the allocated  memory  by cluster version operator",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=\"cluster-version-operator\", cluster=\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Allocations per second",
     "type": "timeseries",
     "description": "Shows the memory allocations per second by  cluster version operator",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"cluster-version-operator\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}