{
 "title": "Openshift / HAProxy",
 "description": "Dashboard shows HAProxy specific metrics for Openshift-ingress namespace",
 "tags": [
  "openshift",
  "openshift-haproxy"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(up,cluster)" } },
   {
    "name": "router",
    "label": "HAProxy Router",
    "query": {
     "query": "label_values(haproxy_up{cluster=\"$cluster\"},pod)"
    }
   },
   {
    "name": "backend",
    "label": "Backend type",
    "query": {
     "query": "label_values(haproxy_backend_bytes_in_total{pod=~\"$router\", cluster=\"$cluster\"},backend)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_bytes_in_total{pod=~\"$router\", cluster=\"$cluster\"},frontend)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{pod=~\"$router\", cluster=\"$cluster\"},code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# This dashboard is designed for Openshift 4.5 and higher\n\n* Platform monitoring is adapted to collect metrics from Openshift 4.5 and higher. Please note, panels don't work in OpenShift v3.11.\n* This dashboard shows metrics of \"HAProxy\" in \"Openshift-ingress\" namespace. Please sure that HAProxy router pods are deployed and running.\n* Also this dashboard shows metrics of \"openshift-state-metrics\" exporter. By default this exporter is deployed in \"openshift-monitoring\" namespace as a deployment. Please sure that this exporter is deployed and running."
     }
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backends Up",
   "type": "stat",
   "description": "Shows amount of instances for current backend with status \"UP\"",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(haproxy_backend_up{cluster=\"$cluster\", backend=~\"$backend\", pod=~\"$router\"} == 1)",
     "legendFormat": "Backends Up"
    }
   ]
  },
  {
   "title": "Current health status of the backends",
   "type": "table",
   "description": "Shows states in time for current backend and route(if exists)",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "haproxy_backend_up{cluster=\"$cluster\",backend=~\"$backend\",pod=~\"$router\"} * on (route) group_left(host)openshift_route_info{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backends DOWN",
   "type": "stat",
   "description": "Shows amount of instances for current backend with status \"DOWN\"",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(haproxy_backend_up{cluster=\"$cluster\",backend=~\"$backend\",pod=~\"$router\"} != 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Basic General Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total responses by HTTP code",
     "type": "timeseries",
     "description": "Shows statistics about total responses from backends and frontends by HTTP codes",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(haproxy_frontend_http_responses_total{cluster=\"$cluster\",frontend=~\"$frontend\",code=~\"$code\",pod=~\"$router\", }[5m])) by (code)",
       "legendFormat": "Frontend {{ code }}"
      },
      {
       "expr": "sum(irate(haproxy_backend_http_responses_total{cluster=\"$cluster\",backend=~\"$backend\",code=~\"$code\",pod=~\"$router\"}[5m])) by (code)",
       "legendFormat": "Backend {{ code }}"
      }
     ]
    },
    {
     "title": "Current total of incoming / outgoing bytes",
     "type": "timeseries",
     "description": "Shows traffic statistics for backends and frontends",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(irate(haproxy_frontend_bytes_in_total{cluster=\"$cluster\",frontend=~\"$frontend\",pod=~\"$router\"}[5m])) by (pod)",
       "legendFormat": "Frontend IN "
      },
      {
       "expr": "sum(irate(haproxy_frontend_bytes_out_total{cluster=\"$cluster\",frontend=~\"$frontend\",pod=~\"$router\"}[5m])) by (pod)",
       "legendFormat": "Frontend OUT"
      },
      {
       "expr": "sum(irate(haproxy_backend_bytes_in_total{cluster=\"$cluster\",backend=~\"$backend\",pod=~\"$router\"}[5m])) by (pod)",
       "legendFormat": "Backend IN"
      },
      {
       "expr": "sum(irate(haproxy_backend_bytes_out_total{cluster=\"$cluster\",backend=~\"$backend\",pod=~\"$router\"}[5m])) by (pod)",
       "legendFormat": "Backend OUT "
      }
     ]
    },
    {
     "title": "Sessions",
     "type": "timeseries",
     "description": "Shows amount of current sessions and rate for frontends and backends",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(haproxy_frontend_current_sessions{frontend=~\"$frontend\",pod=~\"$router\",cluster=\"$cluster\"}) by (pod)",
       "legendFormat": "Frontend current sessions"
      },
      {
       "expr": "sum(haproxy_frontend_current_session_rate{frontend=~\"$frontend\",pod=~\"$router\",cluster=\"$cluster\"}) by (pod)",
       "legendFormat": "Frontend current session rate"
      },
      {
       "expr": "sum(haproxy_backend_current_sessions{backend=~\"$backend\",pod=~\"$router\",cluster=\"$cluster\"}) by (pod)",
       "legendFormat": "Backend current sessions"
      },
      {
       "expr": "sum(haproxy_backend_current_session_rate{backend=~\"$backend\",pod=~\"$router\",cluster=\"$cluster\"}) by (pod)",
       "legendFormat": "Backend current session rate"
      }
     ]
    },
    {
     "title": "Total number of connections",
     "type": "timeseries",
     "description": "Sows amount of connections and errors(only to backends) to frontends and backends",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(haproxy_frontend_connections_total{frontend=~\"$frontend\",pod=~\"$router\",cluster=\"$cluster\"}[5m])) by (pod)",
       "legendFormat": "Frontend connections"
      },
      {
       "expr": "sum(irate(haproxy_backend_connections_total{backend=~\"$backend\",pod=~\"$router\",cluster=\"$cluster\"}[5m])) by (pod)",
       "legendFormat": "Backend connections"
      },
      {
       "expr": "sum(irate(haproxy_backend_connection_errors_total{backend=~\"$backend\",pod=~\"$router\",cluster=\"$cluster\"}[5m])) by (pod)",
       "legendFormat": "Backend connections errors"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Back - Current total of incoming / outgoing bytes",
     "type": "timeseries",
     "description": "Shows detailed traffic statistics for backends",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(haproxy_backend_bytes_in_total{backend=~\"$backend\",pod=~\"$router\",cluster=\"$cluster\"}[5m])",
       "legendFormat": "IN-{{ backend }}-{{route}}"
      },
      {
       "expr": "irate(haproxy_backend_bytes_out_total{backend=~\"$backend\",pod=~\"$router\",cluster=\"$cluster\"}[5m])",
       "legendFormat": "OUT-{{ backend }}-{{route}}"
      }
     ]
    },
    {
     "title": "Front - Current total of incoming / outgoing bytes",
     "type": "timeseries",
     "description": "Shows traffic statistics per frontend",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",pod=~\"$router\",cluster=\"$cluster\"}[5m])",
       "legendFormat": "IN-{{ frontend }}"
      },
      {
       "expr": "irate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",pod=~\"$router\",cluster=\"$cluster\"}[5m])",
       "legendFormat": "OUT-{{ frontend }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Backends - Total number of connections OK / Error",
     "type": "timeseries",
     "description": "Shows statistics about connections and errors per backend",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(haproxy_backend_connections_total{backend=~\"$backend\",pod=~\"$router\",cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{ backend }} {{route}}"
      },
      {
       "expr": "irate(haproxy_backend_connection_errors_total{backend=~\"$backend\",pod=~\"$router\",cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{ backend }} {{route}} Error"
      }
     ]
    },
    {
     "title": "Frontends - Total number of connections",
     "type": "timeseries",
     "description": "Shows amount of connections per frontend",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(haproxy_frontend_connections_total{cluster=\"$cluster\",frontend=~\"$frontend\", pod=~\"$router\"}[5m])",
       "legendFormat": "{{ frontend }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Backends - Maximum observed number of queued requests ",
     "type": "timeseries",
     "description": "Shows max amount of queued requests per route",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(haproxy_backend_max_queue{backend=~\"$backend\",pod=~\"$router\",cluster=\"$cluster\"}[5m]))",
       "legendFormat": "Max Queue: {{ backend }} {{route}}"
      }
     ]
    },
    {
     "title": "Backends - Current number of queued requests",
     "type": "timeseries",
     "description": "Shows current amount of queued requests per route",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(haproxy_backend_current_queue{backend=~\"$backend\",pod=~\"$router\",cluster=\"$cluster\"}[5m])) by (route)",
       "legendFormat": "Queue: {{ backend }} {{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Backends - Total of re-dispatch / error / retry warnings",
     "type": "timeseries",
     "description": "Shows amount of problems(errors, retry warnings, re dispatch) per route",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(haproxy_backend_redispatch_warnings_total{backend=~\"$backend\",pod=~\"$router\",cluster=\"$cluster\"}[5m])",
       "legendFormat": "Redispatch {{ backend }} {{route}}"
      },
      {
       "expr": "irate(haproxy_backend_retry_warnings_total{backend=~\"$backend\",pod=~\"$router\",cluster=\"$cluster\"}[5m])",
       "legendFormat": "Retry {{ backend }} {{route}}"
      },
      {
       "expr": "irate(haproxy_backend_response_errors_total{backend=~\"$backend\",pod=~\"$router\",cluster=\"$cluster\"}[5m])",
       "legendFormat": "Error {{ backend }} {{route}}"
      }
     ]
    },
    {
     "title": "Frontends- Total HTTP requests OK / Error / Denied",
     "type": "timeseries",
     "description": "Shows amount of requests per status for each frontends",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(haproxy_frontend_http_requests_total{frontend=~\"$frontend\",pod=~\"$router\",cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{ frontend }}"
      },
      {
       "expr": "irate(haproxy_frontend_request_errors_total{frontend=~\"$frontend\",pod=~\"$router\",cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{ frontend }} Error"
      },
      {
       "expr": "irate(haproxy_frontend_requests_denied_total{frontend=~\"$frontend\",pod=~\"$router\",cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{ frontend }} Denied"
      }
     ]
    }
   ]
  },
  {
   "title": "Responses by HTTP code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Backends - Total of HTTP responses",
     "type": "timeseries",
     "description": "Shows amount of responses for backends",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(haproxy_backend_http_responses_total{backend=~\"$backend\", code=~\"$code\",pod=~\"$router\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{ code }} {{ backend }} {{route}}"
      }
     ]
    },
    {
     "title": "Frontends - Total of HTTP responses",
     "type": "timeseries",
     "description": "Shows amount of responses for frontends",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(haproxy_frontend_http_responses_total{frontend=~\"$frontend\", code=~\"$code\",pod=~\"$router\",cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{ code }} {{ frontend }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions Backends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Backends - Current number of active sessions",
     "type": "timeseries",
     "description": "Shows amount of current sessions for backends",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_current_sessions{backend=~\"$backend\",pod=~\"$router\",cluster=\"$cluster\"}",
       "legendFormat": "{{ backend }} {{ route }}"
      }
     ]
    },
    {
     "title": "Back - Current number of sessions rate per second over last elapsed second",
     "type": "timeseries",
     "description": "Shows amount of sessions rate per second over last elapsed second for backends",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_current_session_rate{backend=~\"$backend\",pod=~\"$router\", cluster=\"$cluster\"}",
       "legendFormat": "{{ backend }} {{route}}"
      }
     ]
    },
    {
     "title": "Backends - Maximum observed number of active sessions and limit",
     "type": "timeseries",
     "description": "Shows max  amount of active sessions and limit for backends",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_sessions{backend=~\"$backend\",pod=~\"$router\",cluster=\"$cluster\"}",
       "legendFormat": "MAX: {{ backend }} {{route}}"
      },
      {
       "expr": "haproxy_backend_limit_sessions{backend=~\"$backend\",pod=~\"$router\",cluster=\"$cluster\"}",
       "legendFormat": "Limit: {{ backend }} {{route}}"
      }
     ]
    },
    {
     "title": "Backends - Maximum number of sessions rate per second",
     "type": "timeseries",
     "description": "Shows max amount of sessions rate per second for backends",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_session_rate{backend=~\"$backend\",pod=~\"$router\", cluster=\"$cluster\"}",
       "legendFormat": "{{ backend }} {{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions Frontends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Current number of active sessions",
     "type": "timeseries",
     "description": "Shows amount  of active sessions for frontends",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_frontend_current_sessions{frontend=~\"$frontend\",pod=~\"$router\",cluster=\"$cluster\"}",
       "legendFormat": "{{ frontend }}"
      }
     ]
    },
    {
     "title": "Front - Current number of sessions rate per second over last elapsed second",
     "type": "timeseries",
     "description": "Shows amount of sessions rate per second over last elapsed second for frontends",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_frontend_current_session_rate{frontend=~\"$frontend\",pod=~\"$router\", cluster=\"$cluster\"}",
       "legendFormat": "{{ frontend }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of active sessions and limit",
     "type": "timeseries",
     "description": "Shows max amount of active sessions and limit for frontends",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_frontend_max_sessions{frontend=~\"$frontend\",pod=~\"$router\",cluster=\"$cluster\"}",
       "legendFormat": "MAX: {{ frontend }}"
      },
      {
       "expr": "haproxy_frontend_limit_sessions{frontend=~\"$frontend\",pod=~\"$router\",cluster=\"$cluster\"}",
       "legendFormat": "Limit: {{ frontend }} limit"
      }
     ]
    },
    {
     "title": "Front - Maximum number of sessions rate per second and limit",
     "type": "timeseries",
     "description": "Shows max amount of sessions rate per second and limit for frontends",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_frontend_max_session_rate{frontend=~\"$frontend\",pod=~\"$router\",cluster=\"$cluster\"}",
       "legendFormat": "{{ frontend }}"
      },
      {
       "expr": "haproxy_frontend_limit_session_rate{frontend=~\"$frontend\",pod=~\"$router\",cluster=\"$cluster\"}",
       "legendFormat": "{{ frontend }} limit"
      }
     ]
    }
   ]
  }
 ]
}