{
 "title": "Operators Overview",
 "description": "Shows information about operators in the cloud based on operator-sdk.",
 "tags": [
  "self-monitor",
  "operators"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up,cluster)" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{cluster=~\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Reconcile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reconcile Time",
   "type": "timeseries",
   "description": "Shows average time for reconcile by controller in the last 10 min.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(controller_runtime_reconcile_time_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\"}[10m])/rate(controller_runtime_reconcile_time_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\"}[10m])) > 0 ",
     "legendFormat": "{{container}} - {{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Count",
   "type": "timeseries",
   "description": "Shows count of reconcile the last 2 min by controller.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=~\"$cluster\", namespace=~\"$namespace\", result=~\"requeue|requeue_after|success\"}[2m])) by (namespace, container, controller) > 0",
     "legendFormat": "{{container}} - {{controller}}"
    },
    {
     "expr": "increase(prometheus_operator_reconcile_operations_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[2m]) > 0",
     "legendFormat": "{{container}} - {{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Error",
   "type": "timeseries",
   "description": "Shows count of reconcile with error the last 2 min by controller.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=~\"$cluster\", namespace=~\"$namespace\", result=~\"error\"}[2m])) by (namespace, container, controller) ",
     "legendFormat": "{{container}} - {{controller}}"
    },
    {
     "expr": "increase(prometheus_operator_reconcile_errors_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[2m])",
     "legendFormat": "{{container}} - {{controller}}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percentage of HTTP request by code: 2xx or 3xx",
     "type": "timeseries",
     "description": "Shows the percentage of successful requests with status codes 2xx-3xx",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(rate(rest_client_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container!=\"\", code=~\"2..|3..\"}[5m])) by (method, container) > 0 ) / (sum(rate(rest_client_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container!=\"\"}[5m])) by (method, container)) ",
       "legendFormat": "{{method}}: {{container}}"
      },
      {
       "expr": "rate(prometheus_operator_kubernetes_client_http_requests_total{namespace=~\"$namespace\", status_code=~\"2..|3..\"}[5m]) / rate(prometheus_operator_kubernetes_client_http_requests_total{namespace=~\"$namespace\"}[5m]) > 0",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Count of HTTP request by code: 2xx or 3xx",
     "type": "timeseries",
     "description": "Shows count of successful requests with status codes 2xx-3xx in the last 5 min.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(rest_client_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container!=\"\", code=~\"2..|3..\"}[5m])) by (method, container, code) > 0 ",
       "legendFormat": "{{method}}: {{container}} - {{code}}"
      },
      {
       "expr": "increase(prometheus_operator_kubernetes_client_http_requests_total{namespace=~\"$namespace\", status_code=~\"2..|3..\"}[5m]) > 0",
       "legendFormat": "{{container}} - {{status_code}}"
      }
     ]
    },
    {
     "title": "Percentage of HTTP request by code: 4xx or 5xx",
     "type": "timeseries",
     "description": "Shows the percentage of unsuccessful requests with status codes 4xx-5xx",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(rate(rest_client_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container!=\"\", code=~\"4..|5..\"}[5m])) by (method, container) > 0 ) / (sum(rate(rest_client_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container!=\"\"}[5m])) by (method, container)) ",
       "legendFormat": "{{method}}: {{container}}"
      },
      {
       "expr": "rate(prometheus_operator_kubernetes_client_http_requests_total{namespace=~\"$namespace\", status_code=~\"4..|5..\"}[5m]) / rate(prometheus_operator_kubernetes_client_http_requests_total{namespace=~\"$namespace\"}[5m]) > 0",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Count of HTTP request by code: 4xx or 5xx",
     "type": "timeseries",
     "description": "Shows count of unsuccessful requests with status codes 4xx-5xx in the last 5 min.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(rest_client_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container!=\"\", code=~\"4..|5..\"}[5m])) by (method, container, code) > 0 ",
       "legendFormat": "{{method}}: {{container}} - {{code}}"
      },
      {
       "expr": "increase(prometheus_operator_kubernetes_client_http_requests_total{namespace=~\"$namespace\", status_code=~\"4..|5..\"}[5m]) > 0",
       "legendFormat": "{{container}}  - {{status_code}}"
      }
     ]
    }
   ]
  }
 ]
}