{
 "title": "TLS Status",
 "description": "Shows TLS statuses for all services in the cluster",
 "tags": [
  "k8s",
  "tls"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels{cluster=\"$cluster\", label_app_kubernetes_io_name=~\".+\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Help",
     "type": "text",
     "description": "A detailed description for the dashboard",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# Dashboard description\n\nThis dashboard shows all services on the cluster and their TLS statuses.\n\nService names are taken from the common required Kubernetes label `app.kubernetes.io/name` from pods.\n\n**NOTE:** All panels on the dashboard use filter `label_app_kubernetes_io_name=~\".+\"` which means that the dashboard will ignore all **services without `app.kubernetes.io/name` label!**\n\nTLS statuses are taken from `app.kubernetes.io/tls` label from pods.\nThe dashboard can display 3 different TLS states:\n\n* `Enabled`: pods of the service have `app.kubernetes.io/tls: \"true\"` label\n* `Disabled`: pods of the service have `app.kubernetes.io/tls: \"false\"` label\n* `Unknown`: pods don't have `app.kubernetes.io/tls` label"
     }
    }
   ]
  },
  { "title": "TLS Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "All services",
   "type": "stat",
   "description": "Number of all services\n\n(pods with unique `app.kubernetes.io/name` labels)",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group(kube_pod_labels{cluster=\"$cluster\", namespace=~\"$namespace\", label_app_kubernetes_io_name=~\".+\"}) by (namespace, label_app_kubernetes_io_name, label_app_kubernetes_io_tls)) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "List of TLS Statuses",
   "type": "table",
   "description": "Shows names of services (by `app.kubernetes.io/name` label) and their TLS statuses (by `app.kubernetes.io/tls` label)",
   "gridPos": { "h": 20, "w": 20, "x": 4, "y": 2 },
   "targets": [
    {
     "expr": "label_replace(group(\r\n  kube_pod_labels{cluster=\"$cluster\", namespace=~\"$namespace\", label_app_kubernetes_io_name=~\".+\"}\r\n)\r\nby (namespace, label_app_kubernetes_io_name, label_app_kubernetes_io_tls), \"label_app_kubernetes_io_tls\", \"unknown\", \"label_app_kubernetes_io_tls\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TLS enabled",
   "type": "stat",
   "description": "Number of services with enabled TLS\n\n(pods have `app.kubernetes.io/tls: true` label)",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group(kube_pod_labels{cluster=\"$cluster\", namespace=~\"$namespace\", label_app_kubernetes_io_name=~\".+\", label_app_kubernetes_io_tls=\"true\"}) by (namespace, label_app_kubernetes_io_name, label_app_kubernetes_io_tls)) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TLS disabled",
   "type": "stat",
   "description": "Number of services with disabled TLS\n\n(pods have `app.kubernetes.io/tls: false` label)",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group(kube_pod_labels{cluster=\"$cluster\", namespace=~\"$namespace\", label_app_kubernetes_io_name=~\".+\", label_app_kubernetes_io_tls=\"false\"}) by (namespace, label_app_kubernetes_io_name, label_app_kubernetes_io_tls)) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TLS status unknown",
   "type": "stat",
   "description": "Number of services with unknown TLS status\n\n(pods with empty or null `app.kubernetes.io/tls` label)",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group(kube_pod_labels{cluster=\"$cluster\", namespace=~\"$namespace\", label_app_kubernetes_io_name=~\".+\", label_app_kubernetes_io_tls=\"\"}) by (namespace, label_app_kubernetes_io_name, label_app_kubernetes_io_tls)) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}