{{- if .Values.tlsEnabled }}
{{- if and (not .Values.vmAlertManager.tlsConfig.existingSecret) .Values.vmAlertManager.tlsConfig.generateCerts .Values.vmAlertManager.tlsConfig.generateCerts.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vmalertmanager-tls-certificate
  labels:
    app.kubernetes.io/name: vmalertmanager-tls-certificate
    app.kubernetes.io/instance: {{ cat "vmalertmanager-tls-certificate-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: vmAlertManager
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  secretName: {{ default "vmalertmanager-tls-secret" .Values.vmAlertManager.tlsConfig.generateCerts.secretName }}
  duration: {{ default 365 .Values.vmAlertManager.tlsConfig.generateCerts.duration | mul 24 }}h
  renewBefore: {{ default 15 .Values.vmAlertManager.tlsConfig.generateCerts.renewBefore | mul 24 }}h
  commonName: vmalertmanager-crt
  isCA: false
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - localhost
    - vmalertmanager-k8s
    - vmalertmanager-k8s.{{ .Release.Namespace }}.svc
  {{- if gt (.Values.vmAlertManager.replicas | int) 1 }}
  {{- $namespace := .Release.Namespace }}
  {{- range $i, $r := until (int .Values.vmAlertManager.replicas) }}
    - vmalertmanager-k8s-{{ $i }}.vmalertmanager-k8s.{{ $namespace }}.svc
  {{- end }}
  {{- end }}
  {{- if .Values.vmAlertManager.ingress.install }}
    - {{ .Values.vmAlertManager.ingress.host }}
  {{- end }}
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: {{ .Values.clusterIssuerName }}
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
{{- end }}