# This is a YAML-formatted file.
# All parameters specify only as example

promxy:
  install: true
  config:
    serverGroups:
      - address: vmsingle-k8s:8429
        label: k8s-1
      - address: vmsingle-k8s.monitoring.svc.cluster-2.local:8429
        scheme: http
        label: k8s-2

# For another side you need to use the same configuration, except "serverGroups"
# In the "serverGroups" need to swap addresses, like following:
#
# promxy:
#   config:
#     serverGroups:
#       - address: vmsingle-k8s:8429
#         label: k8s-2
#       - address: vmsingle-k8s.monitoring.svc.cluster-1.local:8429
#         scheme: http
#         label: k8s-1
